spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/codesync
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=codesync
spring.rabbitmq.password=codesync

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/codesync
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/codesync/protocol/openid-connect/certs

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

brasil-api.url=https://brasilapi.com.br/api
keycloak-api.url=http://localhost:8081

keycloak.realm=codesync
keycloak.client-id=codesync-backend
keycloak.client-secret=Zp2Fw4Ei4lFq96GaEdAehSqCcp4epBHj

spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=240s


aws.s3.endpoint-url=http://localhost:4566
aws.s3.region=us-east-1
aws.s3.access-key=test
aws.s3.secret-key=test
aws.s3.bucket-evidences-name=codesync-task-evidences
aws.s3.bucket-attachments-name=codesync-task-attachments
aws.s3.bucket-resources-name=codesync-task-resources
