spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/codesync
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres
spring.datasource.password=123456789

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=codesync
spring.rabbitmq.password=codesync

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/codesync
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/codesync/protocol/openid-connect/certs

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

brasil-api.url=https://brasilapi.com.br/api
keycloak-api.url=http://localhost:8081

keycloak.realm=codesync
keycloak.client-id=codesync-backend
keycloak.client-secret=Zp2Fw4Ei4lFq96GaEdAehSqCcp4epBHj

spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=290s